### ISSUE TITLE
Error when running 'docker-compose up'

### ISSUE THREAD

**Issue by North15** [CiviWiki/OpenCiviWiki#911] opened 2021-06-07 21:12 UTC
#### Issue
---
When I run ```docker-compose up``` I get the following error:

```
civiwiki-backend | Traceback (most recent call last):
civiwiki-backend |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
civiwiki-backend |     self.run()
civiwiki-backend |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
civiwiki-backend |     self._target(*self._args, **self._kwargs)
civiwiki-backend |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
civiwiki-backend |     fn(*args, **kwargs)
civiwiki-backend |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
civiwiki-backend |     autoreload.raise_last_exception()
civiwiki-backend |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
civiwiki-backend |     raise _exception[1]
civiwiki-backend |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
civiwiki-backend |     autoreload.check_errors(django.setup)()
civiwiki-backend |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
civiwiki-backend |     fn(*args, **kwargs)
civiwiki-backend |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
civiwiki-backend |     apps.populate(settings.INSTALLED_APPS)
civiwiki-backend |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
civiwiki-backend |     app_config = AppConfig.create(entry)
civiwiki-backend |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
civiwiki-backend |     module = import_module(entry)
civiwiki-backend |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
civiwiki-backend |     return _bootstrap._gcd_import(name[level:], package, level)
civiwiki-backend |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
civiwiki-backend |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
civiwiki-backend |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
civiwiki-backend | ModuleNotFoundError: No module named 'taggit'
```
I'm not sure what the error is referring to, but I cannot seem to get it fixed. I made sure that I have ```django-taggit``` installed and everything looks good on that side.

Any thoughts?

Thanks

**Comment by pscheid2** [comment] 2021-06-17 14:17
Hey @North15! I was just able to get the site running with `docker-compose up` on the `develop` branch.

Can you try `docker-compose build` or deleting the current docker containers in the docker for desktop app and then rerunning docker-compose up?

**Comment by brylie** [comment] 2021-06-18 14:13
@North15 same here. Make sure you are using the latest `develop` branch. We can probably close this issue, as it may have been resolved with recent changes.

**Comment by pscheid2** [comment] 2021-07-13 01:00
@North15 I'm going to close this issue since we aren't able to reproduce on the latest develop branch. Please comment or reopen if your still stuck!

**Closed as completed by pscheid2** 2021-07-13 01:00 UTC
