### ISSUE TITLE
{FEAT}: Automated testing with actions.

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1024] opened 2021-09-20 08:34 UTC
### Idea summary

Usage of GitHub actions.

### Further details

We can use GitHub Actions to check/test the code that is being pushed upstream via PRs and it can be tested before merging automatically (Technically it is Continuous Integration).

**Comment by wassafshahzad** [comment] 2021-09-21 19:54
If this issue is open, I can take a look at it.
However I think i would be better to get @brylie  input on this

**Comment by AbhijithGanesh** [comment] 2021-09-22 05:29
I do believe it is a simple yet necessary solution which we need. Once brylie approves it would be useful if you make files for the workflow yml. I would like to review the same though.

**Comment by brylie** [comment] 2021-09-22 09:37
I agree this is an important issue. It is also a duplicate of #146. @wassafshahzad I'll assign you to this issue and close #146

**Comment by AbhijithGanesh** [comment] 2021-09-22 09:41
Thanks for closing #146, I believe it was left unattended or it wasn't upgraded for Actions.

**Comment by gorkemarslan** [comment] 2021-09-22 10:38
One thing to note: `api` app has a [test](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/tests/test_propublica.py) file that is obsolete. For example, (at least) one package imported by this test file is missing, so the project itself does not include it. Running the tests of the whole project gives an error for this reason. Since, I am now working on unit tests for initially `accounts` app (issue #952), I run tests for only `accounts` app. So you should do the same thing for now. 

@brylie, what can we do about tests in `api` app? We can remove it. Or we won't run its tests? Or, if we use the related part which is tested in the future, we try to solve the problem?

**Comment by brylie** [comment] 2021-09-22 11:06
> what can we do about tests in api app?

I'm in favor of removing obsolete code. As we deprecate the `api` app, we can make sure the code we move to proper apps has good test coverage.

**Comment by gorkemarslan** [comment] 2021-09-22 11:22
`ProPublicaAPI` is the missing module that is imported there. Our project does not have such a module. Are we going to use this module in the future? If not, I will remove it safely.

**Comment by wassafshahzad** [comment] 2021-09-22 11:24
I would remove the unwanted code in my pr as well

**Comment by brylie** [comment] 2021-09-22 11:25
> ProPublicaAPI is the missing module that is imported there.

ProPublica has been removed #857. Feel free to remove that API/test code as well.

**Comment by wassafshahzad** [comment] 2021-09-24 20:49
I have removed the test module from api, should I remove the test_framework as well ?

**Comment by brylie** [comment] 2021-09-25 06:58
>  should I remove the test_framework as well ?

Yes, clean up any unused test code. We will be adding tests within the new Django apps.

**Comment by wassafshahzad** [comment] 2021-09-25 21:32
Hey, @brylie  PR is up.
I also wanted to recommend some changes in our testing methodology.
We should probably use pytest cause of its parametrize functionality, We can write one test for multiple branching paths reducing out code footprint

**Comment by gorkemarslan** [comment] 2021-09-27 06:01
I generally use the standard Django `django.test.TestCase` module. For most of the time, it is sufficient to catch a good test coverage. The number of tutorials on `TestCase` is more than `pytest`. At least for now, we should keep testing with `TestCase`. In this way, more people can contribute to testing, so we should follow what the standard one is. In my opinion, we should focus on improving test coverage as soon as possible. This is easily achievable with the standard one. After that, we can seek for the better method. 

Can you elaborate the advantages of `pytest` a bit more? Is it more useful in the case of test automation? I am open to your opinions to learn which one is beneficial.

**Closed as completed** 2021-09-27 08:47 UTC
Labels: help wanted, in progress, community, mentoring, triage
