### ISSUE TITLE
Unsightly messy scroll bars

### ISSUE THREAD

**Issue by Shreyas4991** [CiviWiki/OpenCiviWiki#230] opened 2018-11-01 19:13 UTC
The multiple scrollable elements on a page each have their scroll bar which is visible in the corner, particularly on Firefox 63 with dark theme. Further it makes little sense to have to look out for a mouse pointer to know which window is going to scroll up or down when one presses the arrow key. May I suggest having one active element at a time, highlighting the active element's borders, and providing keyboard shortcuts to switch between them, as well as customised scroll bars.

**Comment by brylie** [comment] 2018-11-02 09:54
Thanks @Shreyas94. Would you consider providing a screenshot of the current UI and wireframe of the suggested UI to this issue, to help steer the design process?

**Comment by Shreyas94** [comment] 2018-11-02 14:44
![image](https://user-images.githubusercontent.com/4014341/47921904-c2ab2400-dedb-11e8-8c14-d31cc98bce3e.png)
Here's a screenshot.

**Comment by Shreyas94** [comment] 2018-11-04 18:45
1. For the scrollbars, apparently firefox doesn't offer custom scroll bars so some jquery plugin like [this](https://plugins.jquery.com/scrollbar/) might be needed to get a uniform look across all browsers.
2. As for the box in focus, I guess it would useful to have a mild gray or light purple shadow on the active or focussed element. 

This should fix it for the moment.

**Comment by brylie** [comment] 2018-11-04 20:56
@Shreyas94 would you like to take a try at this issue? I am available for pair-programming on weekends, via [Codebuddies.org](https://codebuddies.org/).

**Comment by abhi12ravi** [comment] 2019-04-22 09:34
Hi @brylie I'd like to work on this issue. Is this issue still relevant and are you still available for pair-programming?

**Comment by brylie** [comment] 2019-04-22 09:39
@abhi12ravi sure. What is your timezone? Can you go ahead and set up a development environment?

**Comment by brylie** [comment] 2019-04-22 11:19
@abhi12ravi sure. What is your timezone? Can you go ahead and set up a development environment?

From the issue, it is not clear to me what we should change, as we have content that will span vertical columns.

**Comment by brentkwade** [comment] 2019-04-25 14:32
@brylie did you guys end up working on this issue?

**Comment by brylie** [comment] 2019-04-25 18:12
@brentkwade no, we haven't started. Are you interested in helping with the task?

**Comment by brentkwade** [comment] 2019-04-25 21:27
@brylie Yes I would like to help

**Comment by danielotieno** [comment] 2019-04-25 22:51
Can I join you guys?

**Comment by brylie** [comment] 2019-04-26 09:56
@danielgrijalva sure. Please start by setting up a development environment with these instructions:
https://github.com/CiviWiki/OpenCiviWiki/blob/dev/readmes/docker-setup.md

**Comment by danielotieno** [comment] 2019-04-26 10:12
@brylie Thank you, I will be contributing for the first time.

**Comment by brylie** [comment] 2019-05-10 21:19
@all-contributors please add @Shreyas4991 for idea

**Comment by Hardik500** [comment] 2019-07-30 17:43
Can I join in if the issue is not fixed?

**Comment by brylie** [comment] 2019-07-31 01:46
Sure. How would you like to approach the issue?

**Comment by brylie** [comment] 2019-07-31 01:47
Sure. What would be your recommendation for fixing the scrollbars?

**Comment by Hardik500** [comment] 2019-07-31 15:31
My guess is when ever the page loads we set the first tab as an active one and set a shortcut maybe like "ctrl+shift" or any other to switch between the tabs.
As for different colors in scrollbars I couldn't seem to replicate it on my device.

**Comment by oladhari** [comment] 2019-08-27 09:45
I have no idea how to resolve this problem as I am beginner developer but I would like to investigate and work on it, I see many comments for developers who want to contribute but I guess nobody has started yet
I would like to install the application locally on following [this documentation](https://github.com/CiviWiki/OpenCiviWiki/blob/dev/readmes/local-setup.md)
and this weekend will investigate and give my feedback, is that ok?

**Comment by oladhari** [comment] 2019-08-27 09:46
please, when you reply to my message could you mention my GitHub username so I can get the notification? it is @oladhari 
thank you for understanding

**Comment by brylie** [comment] 2019-08-27 16:28
@oladhari let us know when you get the software running :-)

**Comment by oladhari** [comment] 2019-08-28 00:34
@brylie thank you very much, I will try to install it this evening and let you know

**Comment by oladhari** [comment] 2019-08-29 00:42
@brylie 
I succeeded to build the image with docker-compose up and the application is running correctly locally
<details>
<summary>screen shot of the app running locally</summary>

![Screenshot from 2019-08-29 09-40-19](https://user-images.githubusercontent.com/13581057/63901839-5177c700-ca41-11e9-9439-46cc4e681732.png)
</details>

can we discuss the error when you have time?

**Comment by brylie** [comment] 2019-08-29 07:32
@oladhari FWIW, this isn't really an error, as it is more of a design choice. The original designers decided to split the Civi view into three columns, with the right columns showing related content when a user clicks something in the leftwards column(s).

An alternative approach could be to use nesting, where related content is shown nested within, or connected to, the parent. This might also work a bit better on mobile.

Have you created initial "dummy" content on your local deployment, so you can see how the design functions?

**Comment by ihavenoideaforusername** [comment] 2019-09-10 16:20
hello, i'm totally newcomer, can someone help me to get in? 
i wan't to start programming in python, i'm during complete python course by Jose Salvatierra so i know a bit about python

**Comment by ihavenoideaforusername** [comment] 2019-09-10 16:26
can i join too? i'm first-timer :D

**Comment by cYph3r1337** [comment] 2019-10-18 10:53
Is this still an issue? 
I would like to contribute.

**Comment by brylie** [comment] 2019-10-19 19:10
Sure. What kind of design would you consider for this task?

**Comment by JvPy** [comment] 2019-12-05 19:32
Still open? If so, I may have an idea and would like to contribute

**Comment by brylie** [comment] 2019-12-06 00:13
Sure, although there hasn't been a clear design proposal. Do you have any suggestions?

**Comment by JvPy** [comment] 2019-12-06 00:23
If I understood correctly, the problem with this issue is the user knowing where his scroll will take effect, right?

If so, we can use js to make a border around the selected scroll area

**Comment by brylie** [comment] 2019-12-06 17:59
OK, that sounds sensible, and not too much change.

**Comment by JvPy** [comment] 2019-12-06 18:05
OK. I'll fork the project and give it a try on sunday

**Comment by ali1810** [comment] 2020-02-25 18:11
Hello ,

Is this problem  still exist  then let me try from my end

**Comment by brylie** [comment] 2020-02-25 20:10
We are going to close this issue soon unless there is some concrete progress. Go ahead and open a pull request with any changes.

**Comment by wbenfie** [comment] 2020-03-09 16:33
I would like to work on this issue

**Comment by Abdullah-alfadhel** [comment] 2020-03-12 10:57
Hello, I was wondering if you want an Arabic translator? so the project can reach a wider audience.

**Comment by brylie** [comment] 2020-03-12 11:12
@Abdullah-alfadhel that is a great suggestion. Right now we don't have multi-lingual capabilities. I will create a ticket so we can add internationalization.

Closing this issue as it hasn't received any traction.

**Closed by brylie** 2020-03-12 11:12 UTC
Labels: enhancement, good first issue, help wanted, mentoring
