### ISSUE TITLE
Can't Publish New Thread

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#477] opened 2019-05-13 18:53 UTC
I attempted to make a new thread on Civiwiki.org. I was able to create the content, but when I hit publish it throws a server error. 

![image](https://user-images.githubusercontent.com/30572202/57983784-ba53aa00-7a23-11e9-8e32-a036612b47b3.png)

**Comment by brylie** [comment] 2019-05-13 18:58
Is there any error in your browser console (F12)? What is the server error? Please provide the texts.

**Comment by mdwest** [comment] 2019-05-13 20:31
I just managed to get this uploaded. Not sure why it didn't work earlier

**Comment by brylie** [comment] 2019-05-14 06:19
This should now be fixed by Tomasz' PR, just merged into develop. Pleasr test again on civiwiki-dev.

**Comment by brylie** [comment] 2019-05-18 08:52
@mdwest this may now be resolved by the recent deployment. Please verify.

**Comment by mdwest** [comment] 2019-05-18 12:01
Currently traveling, but I'll check asap.

-mw

**Comment by brylie** [comment] 2019-05-19 07:05
@mdwest verified by email that this issue still affects the `dev` branch, despite us reverting to the previous version.

@mdwest please set up a Sentry account for CiviWiki, so we can track server errors.

**Comment by brylie** [comment] 2019-05-19 07:19
@mdwest I am able to add a thread on `civiwiki-dev` please provide exact steps you followed, describing buttons you clicked and form elements you used, so we can narrow down this issue.

**Comment by brylie** [comment] 2019-05-19 07:31
OK, it looks like Sentry has been configured for CiviWiki, but I am unable to access the Sentry logs. @mdwest can you invite me to the CiviWiki Sentry team?

**Comment by SunflowerPKU** [comment] 2019-05-19 11:59
@brylie 
I have tested this issue. When I click on publish button, it occurs an server error, as following. 
Some icons can not be displaied either, e.g., keyboard_arrow_down.

![image](https://user-images.githubusercontent.com/23006864/57981870-fa407e80-7a6f-11e9-81a3-3cef8a570c02.png)

**Comment by brylie** [comment] 2019-05-19 12:03
OK, thanks for reproducing @SunflowerPKU. Would you like to try and diagnose this error on the server-side? E.g. see if you can get a console log or other output for the specific server error.

**Comment by brylie** [comment] 2019-05-22 20:23
I finally got the project to run locally again, and got the following error in the server console when trying to publish a  thread:

```
Editing thread
civiwiki-db | ERROR:  null value in column "title" violates not-null constraint
civiwiki-db | DETAIL:  Failing row contains (1, null, null, 2019-05-22 20:12:18.333649+00, 2019-05-22 20:19:40.302053+00, 1, null, 0, 0, 2, , null, null, t).
civiwiki-db | STATEMENT:  UPDATE "api_thread" SET "author_id" = 1, "category_id" = NULL, "title" = NULL, "summary" = NULL, "image" = '', "level" = NULL, "state" = NULL, "created" = '2019-05-22T20:12:18.333649+00:00'::timestamptz, "last_modified" = '2019-05-22T20:19:40.302053+00:00'::timestamptz, "is_draft" = true, "num_views" = 2, "num_civis" = 0, "num_solutions" = 0 WHERE "api_thread"."id" = 1
civiwiki-backend | null value in column "title" violates not-null constraint
civiwiki-backend | DETAIL:  Failing row contains (1, null, null, 2019-05-22 20:12:18.333649+00, 2019-05-22 20:19:40.302053+00, 1, null, 0, 0, 2, , null, null, t).
```

**Comment by mdwest** [comment] 2019-05-23 03:07
I just tested the latest code and the publish button now appears to work (no server error message and a message says it is now public and refreshing) but the thread does not actually publish. 

The thread remains in drafts for the publishing account and is not visible on the feed of other accounts.

**Comment by brylie** [comment] 2019-05-24 08:05
@TomaszKolek are you working on this issue?

**Comment by mdwest** [comment] 2019-05-24 21:41
My understanding is tomasz has only proposed researching the issue and we
have not yet agreed on a contract.

-mw

**Comment by brylie** [comment] 2019-05-25 18:08
@TomaszKolek I have made some progress in PR #521, please review. Now, the thread *does* publish successfully, but nothing displays on the CiviWiki home page. There are some errors related to feed.js to work through.

**Closed** 2019-05-26 09:29 UTC
Labels: bug, help wanted, mentoring
