### ISSUE TITLE
Create project base template (base.html)

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1049] opened 2021-09-28 08:49 UTC
### Idea summary

We need a base template to use across apps. The base template should include common CSS, JS, and page elements

### Further details

- [x] create a file in `core/templates/base.html`
    - [x] add boilerplate HTML5 markup (below)
- [ ] change all other primary templates so they extend from `base.html` using `extends` and `{% block content %}` template tags (example below)
    - [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/account_base.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/register/entry_base.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/0b8e5879de1139d3b0fd77b48af0f47fb30a6051/project/accounts/templates/accounts/utils/update_settings.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/partials/account/login.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/general-message.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/user-setup.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/da20141a23f8f089029652f6b451d2c0c69417fe/project/threads/templates/threads/feed.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/48e8a5581f7883dd64026a9dd4cf00970d1d8434/project/threads/templates/threads/user/reset_by_email.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d88357f4d9d71bc0ba9d0ab66e81fd469bc89740/project/threads/templates/threads/static_templates/how_it_works.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/48e8a5581f7883dd64026a9dd4cf00970d1d8434/project/threads/templates/threads/user/password_reset.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/fe74a82af787d34f3c98f085e3bf6530e46bee7b/project/threads/templates/threads/account.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d88357f4d9d71bc0ba9d0ab66e81fd469bc89740/project/threads/templates/threads/user/settings.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/thread.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d88357f4d9d71bc0ba9d0ab66e81fd469bc89740/project/threads/templates/threads/static_templates/support_us.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/da20141a23f8f089029652f6b451d2c0c69417fe/project/threads/templates/threads/static_templates/landing.html
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/d88357f4d9d71bc0ba9d0ab66e81fd469bc89740/project/threads/templates/threads/static_templates/about.html
- [ ] delete the file: https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/threads/templates/threads/base/links.html
- [ ] delete all references to the `threads/base/links.html`
    - [ ] https://github.com/CiviWiki/OpenCiviWiki/search?q=%7B%25+include+%22base%2Flinks.html%22+%25%7D

### Boilerplate HTML5 markup

```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>CiviWiki - {% block page_title %}{% endblock page_title %}</title>
    <meta name="description" content="Building a Better Democracy for the Internet Age">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,600,700" rel="stylesheet">

	 <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
	 <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
	 <link rel="shortcut icon" href="/favicon.ico">
	 <meta name="msapplication-TileImage" content="/mstile-144x144.png">
	 <meta name="msapplication-TileColor" content="#fcffff"> 
	 <link type="text/css" rel="stylesheet" href="{% static "dependencies/materialize.min.css" %}">
	 <link type="text/css" rel="stylesheet" href="{% static "dependencies/magicsuggest-min.css" %}">
	 <script type="text/javascript" src="{% static "dependencies/jquery.min.js" %}"></script>
	 <script type="text/javascript" src="{% static "dependencies/underscore.js" %}"></script>
	 <script type="text/javascript" src="{% static "dependencies/backbone-min.js" %}"></script>
	 <script type="text/javascript" src="{% static "dependencies/materialize.min.js" %}"></script>
	 <script type="text/javascript" src="{% static "dependencies/magicsuggest-min.js" %}"></script>
	 <script type="text/javascript" src="{% static "js/base.js" %}"></script>
	 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
    {% block extra_css %}{% endblock extra_css %}
</head>

<body>
    {% block content %}{% endblock content %}

    {% block extra_js %}{% endblock extra_js %}
</body>
</html>
```

### Extending `base.html` in a child template

In order to extend `base.html` we need to add two things in each relevant child template:

- At the top of the template, add `{% extends `base.html` %}`
- surround remaining content with `{% block content %}` and `{% endblock content %}`
- change any `<title>...</title>` tags to `{% block page_title %}...{% endblock page_title %}`
- if present, delete any `<!doctype html>`, `<head>...</head>`, or `<body>...</body>` markup
    - move the content from `<head>...</head>` to the `base.html`, unless it is already there

**Comment by earthprelude** [comment] 2021-09-28 20:39
Can I try to help with this?

**Comment by brylie** [comment] 2021-09-29 10:05
Sure, @earthprelude. Thanks :smiley:

**Comment by earthprelude** [comment] 2021-09-29 23:18
No problem! :) 

I looked through the files and have a few clarifying questions: 

1. Should extra `<script>` elements in the child templates be placed inside of `{% block extra_js %}{% endblock extra_js %}` or  included as part of `{% block content %} {% endblock content %}`? (For example, the scripts at the end of [`threads/templates/threads/general-message.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/general-message.html))

2. Is `{% block extra_css %}{% endblock extra_css %}` meant to be used for anything in the child templates? Based on the issue description, I just moved all extra css links in the `<head>` section of child templates to `base.html` (if not present there already).

3. Sometimes there seems to be some duplication in `{block page-title}`, because both `base.html` and the child template have "CiviWiki" in the title. (For example, [`threads/templates/threads/partials/account/login.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/partials/account/login.html)). Is it supposed to display CiviWiki-CiviWiki? If not, should I remove CiviWiki from the title of those child templates, or instead make `base.html` more generic by changing the boilerplate from 
`<title>CiviWiki - {% block page_title %}{% endblock page_title %}</title>` 
to 
`<title>{% block page_title %}{% endblock page_title %}</title>`?

4. In some files, the `<body>` tag has specific ID or class attributes. Is it still safe to remove these? In case they are used for styling, should I leave these tags and change them to `<div>` ? For example: [`threads/templates/threads/user/settings.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/d88357f4d9d71bc0ba9d0ab66e81fd469bc89740/project/threads/templates/threads/user/settings.html) and [`threads/templates/threads/general-message.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/general-message.html)

**Comment by brylie** [comment] 2021-09-30 11:46
> Should extra <script> elements in the child templates be placed inside of {% block extra_js %}{% endblock extra_js %}

Yes

**Comment by brylie** [comment] 2021-09-30 11:48
> Is {% block extra_css %}{% endblock extra_css %} meant to be used for anything in the child templates?

It is used for rare cases where a template needs to load some CSS that is only related to the template. E.g a page might display a map or chart that uses CSS but we don't want to download the CSS on every page.

**Comment by brylie** [comment] 2021-09-30 11:50
> Sometimes there seems to be some duplication in {block page-title}, because both base.html and the child template have "CiviWiki" in the title.

In those cases, remove "CiviWiki" from the page title string in the child template. Basically, child templates should only contain their own title, which will be prefixed by "CiviWiki - " from the base template.

**Comment by brylie** [comment] 2021-09-30 11:57
> In some files, the <body> tag has specific ID or class attributes. Is it still safe to remove these?

To play things safe here, change the opening `body` tag in `base.html` as follows.

```html
<body class="{% block body_class %}{% endblock body_class %">
```

Then in the relevant child templates add in the specific class(es) near the top of the template file. E.g.,

```html
{% block body_class %}example-class, another-class{% endblock body_class %}

{% block content %}
    ...
{% endblock content %}

```

**Comment by earthprelude** [comment] 2021-09-30 17:33
Thanks a lot for your clarifications and advice!

> > Is {% block extra_css %}{% endblock extra_css %} meant to be used for anything in the child templates?
> 
> It is used for rare cases where a template needs to load some CSS that is only related to the template. E.g a page might display a map or chart that uses CSS but we don't want to download the CSS on every page.

I see, thanks! In these files, there's some CSS that seems to only be used by a few templates, so I wasn't sure whether I should still put it in `base.html`. For now, I left it in `{% block extra_css %}` for those specific templates.  

Also, I originally moved the `{% load static %}` and `{% load i18n %}` tags I found in the `<head>...</head>` of child templates to `base.html`, but removing these from the templates caused a server error - which is how I learned that [template tags](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#internationalization-in-template-code) still have to be loaded again in child templates, even when they are already loaded in `base.html`. Should I put those tags inside `{% block extra_css %}` in the templates or just on top?

**Comment by earthprelude** [comment] 2021-09-30 18:11
Separately, some child templates like this one ([general_message.html](https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/general-message.html)) have `<script type=text/template>` elements on top of the `<body>` content. I've been including those as part of `{% block content %}`. But would it make sense to add a new, separate block for those to `base.html`? 

E.g.

```
{% block extra_template %}{% endblock extra_template %}
<body class="{% block body_class %}{% endblock body_class %}">
...
</body>
```

**Comment by earthprelude** [comment] 2021-10-01 01:06
> In those cases, remove "CiviWiki" from the page title string in the child template. Basically, child templates should only contain their own title, which will be prefixed by "CiviWiki - " from the base template.

Ok, I did that. Some templates don't have a title, so just to confirm, is it ok for them to have as their default title "CiviWiki - " with the extra dash?

**Comment by brylie** [comment] 2021-10-01 07:25
Yes, but perhaps call it `backbone_template` instead of `extra_template`, so the purpose of the block is clear.

**Comment by earthprelude** [comment] 2021-10-02 01:23
Sounds good, thanks! 

When I ran the tests, there was the following error: 
`django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once`

I believe it is probably caused by the following child template - [`accounts/register/entry_base.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/register/entry_base.html) - which is also serving as a base template for other files, and defines its own set of `{% block content %}` blocks. 

![image](https://user-images.githubusercontent.com/75330343/135699541-b50c2e35-c755-4ab8-ad47-6592dd62e358.png)

Should I use a different name for those blocks created in `entry.html` (e.g. `{% block form_content %}`), and change the name for corresponding blocks in the files that extend from it (`accounts/register/register.html` and `accounts/register/login.html`)? Or is there a different way you would like me to address this?

**Comment by brylie** [comment] 2021-10-02 06:32
We should have only one base template in the project. Try editing `accounts/register/entry_base.html` and adding `{% extends "base.html" %}` at the top.

**Comment by earthprelude** [comment] 2021-10-02 18:29
Oh I had already added that (sorry it wasn't visible in the screenshot). Here is a larger screenshot of `accounts/register/entry_base.html` : 

![image](https://user-images.githubusercontent.com/75330343/135727785-5e0ca17c-c19f-4af8-863b-f4b35cc55c21.png)

When I tried checking the other files inside this folder, there seem to be 2 extra files ([`accounts/register/login.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/register/login.html) and [`accounts/register/register.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/register/register.html)) that currently extend from `entry_base.html` as their base template. Should I change those to extend from `base.html` instead? Then I could also remove the extra `{% block content %}` from `entry_base.html` which is causing the error.

**Comment by earthprelude** [comment] 2021-10-02 20:18
Oh sorry for being unclear, I'd already edited this file to extend `base.html` before running the tests. Here is a larger screenshot of `accounts/register/entry_base.html` in my branch: 

![image](https://user-images.githubusercontent.com/75330343/135727785-5e0ca17c-c19f-4af8-863b-f4b35cc55c21.png)

I believe the problem is that there are now 2 block tags with the same name, **content**. One of them (the `{% block content %}{% endblock %}` inside `<div>`) was already there in the original file, as a placeholder for `entry_base.html`'s own child templates.  The second ones were added when I edited this file to extend `base.html`, and enclosed all the content previously in `<body>` inside a new `{% block content %}...{% endblock content %}`.

When I tried checking the other files inside this folder, there seem to be 2 extra files ([`accounts/register/login.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/register/login.html) and [`accounts/register/register.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/register/register.html)) that currently extend from `entry_base.html` as their parent template. Should I change these to make them extend from `base.html` instead, and just copy over the content they currently inherit from `entry_base.html`? If so, I could also remove the extra `{% block content %}{% endblock %}` that was originally in `entry_base.html`, and prevent the error.

**Comment by brylie** [comment] 2021-10-04 06:36
Any template that includes `block content` should have `{% extends "base.html" %}`  at the top. That way, the `block content` will be placed inside of the existing `block content` from the `base.html`. Please let me know if adding `{% extends "base.html" %}` to the top of the accounts templates resolves this issue.

**Comment by earthprelude** [comment] 2021-10-05 01:14
In this case it doesn't resolve the issue, because there are still 2 `block content` in the same file (`entry_base.html`). 

The cause is that after the update, there are now 2 levels of inheritance, because `entry_base.html` is now both a child template of `base.html`, while also still being a parent template for `accounts/register/register.html` and `accounts/register/login.html`. So `block content` is now being used doubly.

I can see 2 potential solutions: 

1) The simplest change would be to rename the original `block content` used by ` entry_base.html` and its child templates. This block is used as a placeholder for certain forms, so it could be called something like `block form_content` instead. Everything else could remain as it is. However, this also maintains the 2 levels of inheritance. 

2) If the goal is for all files to extend directly from `base.html`, then one solution could be to copy over the HTML content of `entry_base.html` into its child templates, `register.html` and `login.html`. That way, they would no longer need to inherit this content from `entry_base.html`, and could extend directly from `base.html` instead.

**Comment by earthprelude** [comment] 2021-10-05 03:26
For now I can leave out the `entry_base` file, and instead submit a small initial PR which adds the `base.html` template to `core/templates` and just edits the 4 templates inside that folder. Splitting up the PRs will hopefully also help make the review process more manageable on your end.  

For this small group of `core/template` files, there were no problems when I ran the tests, but when I ran the server, at first there was the following result: 
![image](https://user-images.githubusercontent.com/75330343/135950589-bbfc3607-1d36-494c-9008-55da4f373603.png)

I found the reason when I checked inside of `staticfiles/dependencies`, as there don't seem to be any files there yet for `"materialize.min.css"` or `"materialize.min.js"` . So I changed `base.html` to use the external URL for those 2 files, which resolved this error. 

I also found that moving some links from the `<head>...</head>` of child templates into `base.html` caused changes in the appearance of the website (the styles didn't seem to load properly) so I've kept those links inside `{% block extra_css %}...{% endblock %}` in the child templates for now.

**Comment by brylie** [comment] 2021-10-05 08:27
The pull request looks great. I added comments to make one significant change that will reduce duplication of code.

**Comment by earthprelude** [comment] 2021-10-06 01:56
Thanks for the feedback! I updated it.

**Comment by brylie** [comment] 2021-10-06 09:20
One small change to revert to `<!DOCTYPE html>` as per MDN: https://developer.mozilla.org/en-US/docs/Glossary/Doctype

**Comment by earthprelude** [comment] 2021-10-06 22:04
Sure, thanks!

**Comment by brylie** [comment] 2021-10-07 06:50
I approved the PR. If possible, I'd like for @gorkemarslan to take a quick look as well, since they have worked with that code recently.

**Comment by brylie** [comment] 2021-10-07 08:54
I'm reopening this issue until we confirm that all of the checklist items are complete. @earthprelude, please check off the items that you have done so far.

**Comment by earthprelude** [comment] 2021-10-07 23:00
> * [x]  create a file in `core/templates/base.html`
>   
>   * [x]  add boilerplate HTML5 markup (below)
> * [ ]  change all other primary templates so they extend from `base.html` using `extends` and `{% block content %}` template tags (example below)
>   
>   * [ ]   https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/account_base.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/register/entry_base.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/0b8e5879de1139d3b0fd77b48af0f47fb30a6051/project/accounts/templates/accounts/utils/update_settings.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/partials/account/login.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/general-message.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/user-setup.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/da20141a23f8f089029652f6b451d2c0c69417fe/project/threads/templates/threads/feed.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/48e8a5581f7883dd64026a9dd4cf00970d1d8434/project/threads/templates/threads/user/reset_by_email.html
>   * [x]  https://github.com/CiviWiki/OpenCiviWiki/blob/d88357f4d9d71bc0ba9d0ab66e81fd469bc89740/project/threads/templates/threads/static_templates/how_it_works.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/48e8a5581f7883dd64026a9dd4cf00970d1d8434/project/threads/templates/threads/user/password_reset.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/fe74a82af787d34f3c98f085e3bf6530e46bee7b/project/threads/templates/threads/account.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/d88357f4d9d71bc0ba9d0ab66e81fd469bc89740/project/threads/templates/threads/user/settings.html
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/thread.html
>   * [x]  https://github.com/CiviWiki/OpenCiviWiki/blob/d88357f4d9d71bc0ba9d0ab66e81fd469bc89740/project/threads/templates/threads/static_templates/support_us.html
>   * [x]  https://github.com/CiviWiki/OpenCiviWiki/blob/da20141a23f8f089029652f6b451d2c0c69417fe/project/threads/templates/threads/static_templates/landing.html
>   * [x]  https://github.com/CiviWiki/OpenCiviWiki/blob/d88357f4d9d71bc0ba9d0ab66e81fd469bc89740/project/threads/templates/threads/static_templates/about.html
> * [ ]  delete the file: https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/threads/templates/threads/base/links.html
> * [ ]  delete all references to the `threads/base/links.html`
>   
>   * [ ]  https://github.com/CiviWiki/OpenCiviWiki/search?q=%7B%25+include+%22base%2Flinks.html%22+%25%7D

**Comment by earthprelude** [comment] 2021-10-08 01:08
I'm also ready to make another PR that edits the templates in the `threads` folder (`general_message.html` and `thread.html`). It looks like the remaining templates in the list above have all been moved to the `accounts` folder, so I can address that folder next time. 

I just have a quick question. The current base template includes a navigation bar ([`static_nav.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/static_templates/static_nav.html)) after the `<body>` tag. But I noticed that some other templates (e.g. [`thread.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/thread.html)) already include a different HTML file for a navigation bar ([`threads/partials/utils/global_nav.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/partials/utils/global_nav.html)).

![image](https://user-images.githubusercontent.com/75330343/136481661-dc6ee8c6-f11b-47b4-9706-87f7e974d31c.png)

When I edit these templates to extend `base.html`, is it fine to leave `{% include "partials/utils/global_nav.html" %}` inside of `{% block content %}...{% endblock %}`?

**Comment by brylie** [comment] 2021-10-08 07:36
Ok sounds good. Let's take care of the remaining items with a single pull request

**Comment by earthprelude** [comment] 2021-10-09 01:24
Sure, no problem. I made the edits on all the templates listed above, and have a couple updates about some results I saw.

To follow up on the double navigation bars: when I ran the server on my branch, it showed 2 different navigation bars at the same time. For example, after logging in to my account, I saw this mix of navigation bars:
![image](https://user-images.githubusercontent.com/75330343/136638280-8145bc2e-60d0-4322-b189-c2177fa7fd4d.png)
I think the cause is that several child templates include `global_nav.html` for their navigation bar, so they were now also inheriting an extra navigation bar from `static_nav.html` in `base.html`. To prevent this, I tried removing `static_nav.html` from the base template, and letting each child template specify which of the 2 navigation bars to include. Out of the files listed above, only the 4 templates in the `core` folder included `static_nav.html` originally, while most of the other templates include `global_nav.html`. 

After making that change, I can see the regular screen after logging in again: 
![image](https://user-images.githubusercontent.com/75330343/136638690-98e27796-5791-4cfb-8f0a-a67a13688769.png)

**Comment by earthprelude** [comment] 2021-10-09 02:46
> When I ran the tests, there was the following error: `django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once`
> I believe it is probably caused by the following child template - [`accounts/register/entry_base.html`](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/templates/accounts/register/entry_base.html) - which is also serving as a base template for other files, and defines its own set of `{% block content %}` blocks.

I searched further and found that `entry_base.html` is currently the parent template for 6 child templates (which are not part of the list above). In order to resolve the syntax error, while avoiding duplication of code, I think the fastest solution is to rename the empty blocks in `entry_base.html` that are filled in by its child templates as `{% block entry_content %}{endblock}`. This solution leaves 2 levels of template inheritance, but I just saw that the Django documentation recommends multiple inheritance to maximize code reuse ([`https://docs.djangoproject.com/en/3.2/ref/templates/language/#template-inheritance`](https://docs.djangoproject.com/en/3.2/ref/templates/language/#template-inheritance))

Here is the updated section of `entry_base.html`:
![image](https://user-images.githubusercontent.com/75330343/136639112-83c2137b-f2e2-4cdc-b8b4-2098b780fe35.png)

**Comment by brylie** [comment] 2021-10-11 08:17
`entry_base.html` should extend `base.html` or be removed if there aren't any significant differences.

**Closed as completed** 2021-10-12 07:26 UTC
Labels: enhancement, help wanted, good first issue, community, mentoring
