### ISSUE TITLE
Add Github Project and Github issue link to Static pages 

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#107] opened 2017-12-09 02:59 UTC
I was reading about an open source blockchain project (https://www.openchain.org/) 

I liked how they link their active development issues on the bottom of their static pages. We should add this link to help attract developers.

**Comment by extremelypenguin** [comment] 2017-12-28 05:13
Hey! I'd be interested in this issue. By active development issues you mean things like "current issues we need to solve" etc etc?  It would also be helpful if you could say which file this would concern (which file we'd have to change in order to solve the issue)

**Comment by brylie** [comment] 2017-12-28 09:30
You can start by adding any relevant links to our README.md. That way, we will have a simple way to make progress, with only one file to edit, and will be able to determine which specific information to show.

@mdwest can you give a specific example of a page where you show their development issues?

**Comment by mdwest** [comment] 2017-12-28 15:35
On the other Project, they just linked to github issues (i.e. https://github.com/CiviWiki/OpenCiviWiki/issues) 

But if you don't need a waffle account to view the content I think our waffle board is a better link (https://waffle.io/CiviWiki/OpenCiviWiki)

**Comment by mdwest** [comment] 2017-12-28 15:37
@extremelypenguin Thanks so much for your interest in helping on the project! If you are interested in meeting some of the other developers on the project and getting up to date on development plans you should join us for our weekly development meeting Monday, January 8th at 10am PDT. We meet via video conference at https://meet.jit.si/civiwiki.

**Comment by extremelypenguin** [comment] 2017-12-28 16:08
@brylie when you say relevant links do you mean the issues themselves or the page linking to the issues? the problem is that if you just link to specific issues it will constantly need to be updated 

@mdwest I'd love to get to those meetings but I am still in grade school and that time would be on a school day on school hours.

**Comment by brylie** [comment] 2017-12-28 19:08
Well, we have the link to Waffle.io in our README, which shows prioritized issues. This might also be good to put on static pages identified by @mdwest.

**Comment by jl24** [comment] 2018-04-19 00:02
@extremelypenguin did you ever pick this up? if not I'm going to go ahead and assign it to myself.

**Closed** 2018-05-01 09:16 UTC
Labels: Community, good first issue, in progress
