### ISSUE TITLE
Vote counters don't work as expected

### ISSUE THREAD

**Issue by Unit111** [CiviWiki/OpenCiviWiki#123] opened 2018-02-08 12:03 UTC
While testing I've noticed that the count number for the threads' problems I've opened do not count properly. I was able to generate 40 points by myself using a single account.

**Comment by jl24** [comment] 2018-08-03 01:14
I'm unsure which number this is referring to, but checked both the counter displayed in the civi-outline section and the points present in each of the individual civis, but was unable to replicate this.

**Comment by brylie** [comment] 2018-08-06 14:27
@Unit111 can you clarify this issue description?

**Comment by petarPetrovBG** [comment] 2018-08-06 15:00
I am currently unable to reproduce it on civiwiki.org. 
Previously- by opening the Civi multiple times and changing my vote I the counter was only incrementing without going down during changes.

**Comment by brylie** [comment] 2018-08-07 11:08
OK. Closing this issue, since the neither @jl24 or @petarPetrovBG could reproduce.

**Closed by brylie** 2018-08-07 11:08 UTC
Labels: bug, in progress
