### ISSUE TITLE
[BUG]: Major design issues

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1100] opened 2021-10-05 15:49 UTC
### Description

When I try creating a new thread, the threads donot change and the following messages are console logged.

Major JS components are failing here.

### Further details

![image](https://user-images.githubusercontent.com/67182544/136057656-f64b8eed-4e0c-4d35-99cd-36a275f4fd91.png)

**Comment by gorkemarslan** [comment] 2021-10-05 17:18
I think this is related to #1080.

**Comment by brylie** [comment] 2021-10-06 06:39
Closing as duplicate of #1080

**Closed as completed by brylie** 2021-10-06 06:39 UTC
Labels: duplicate
