### ISSUE TITLE
Migrate threads urls to path

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1077] opened 2021-10-02 06:41 UTC
in `threads` app, we need to change `url()`  function with `path()` function as discussed in #1066

https://github.com/CiviWiki/OpenCiviWiki/blob/d7f24fad7c0a2565da3bf2cd54e89a847d7479dd/project/threads/urls.py#L19-L41

Conversion to [path](https://github.com/CiviWiki/OpenCiviWiki/blob/d7f24fad7c0a2565da3bf2cd54e89a847d7479dd/project/threads/urls.py#L19-L41) is simple.

For example,

```python
url(r"^thread_data/(?P<thread_id>\w+)/$", get_thread, name="get thread"),
```

should become

```python
path("thread_data/(<int:thread_id>/", get_thread, name="get thread"),
```

We need to be changed all usages of `url()` function in `threads` app.

**Comment by rishabhjha708** [comment] 2021-10-02 10:46
Hi @gorkemarslan @brylie , I wanted to raise a PR for this. Can you add me as collaborator. Getting 403 status code.

**Comment by hudson-thomas** [comment] 2021-10-02 13:18
I can work on this.

**Comment by gorkemarslan** [comment] 2021-10-02 15:06
@rishabhjha708, how do you get 403 status code? Could you define in which step you get this error?

@hudson-thomas, @rishabhjha708 comes earlier than you. Could you check other open issues?

**Comment by rishabhjha708** [comment] 2021-10-02 17:08
@gorkemarslan , I am getting this while push a sub-branch.
I created a sub-branch from develop branch and trying to push that but getting this 
```
rishabhjha@Rishabhs-MacBook-Pro OpenCiviWiki % git push --set-upstream origin migrate_thread_urls
Username for 'https://github.com': rishabhjha708
Password for 'https://rishabhjha708@github.com': 
remote: Permission to CiviWiki/OpenCiviWiki.git denied to rishabhjha708.
fatal: unable to access 'https://github.com/CiviWiki/OpenCiviWiki.git/': The requested URL returned error: 403
```

**Comment by rishabhjha708** [comment] 2021-10-02 17:14
Tried  again by creating fresh sub branch from develop still got same
```
rishabhjha@Rishabhs-MacBook-Pro OpenCiviWiki % git add .
rishabhjha@Rishabhs-MacBook-Pro OpenCiviWiki % git commit -m "Migration from url to path"
[migrate_thread a5e795a] Migration from url to path
 1 file changed, 16 insertions(+), 16 deletions(-)
rishabhjha@Rishabhs-MacBook-Pro OpenCiviWiki % git push
fatal: The current branch migrate_thread has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin migrate_thread

rishabhjha@Rishabhs-MacBook-Pro OpenCiviWiki % git push --set-upstream origin migrate_thread
Username for 'https://github.com': rishabhjha708
Password for 'https://rishabhjha708@github.com': 
remote: Permission to CiviWiki/OpenCiviWiki.git denied to rishabhjha708.
fatal: unable to access 'https://github.com/CiviWiki/OpenCiviWiki.git/': The requested URL returned error: 403
```

**Comment by gorkemarslan** [comment] 2021-10-02 17:21
@rishabhjha708, are you given this error when you push other repos? I think the problem is with your local computer. It is not permitted to make changes on your GitHub account. Did you download SSH keys from your GitHub account to your computer? 

Could you look at this [answer](https://github.com/trilbymedia/grav-plugin-git-sync/issues/39#issuecomment-546016249)? (And of course other answers, as well)

**Comment by gorkemarslan** [comment] 2021-10-02 17:31
@rishabhjha708, for future reference, was the problem solved by the answer above? If not, please tell us how to handle it. Then we can help the contributors who will get the same error in the future.

**Comment by rishabhjha708** [comment] 2021-10-02 17:35
yes @gorkemarslan  the issue was that only, raising PR..

**Comment by Vinit-Kumar-Shah** [comment] 2021-10-02 17:43
@gorkemarslan I understand what to do in this task please assign this task to me so I can work on this issue

**Comment by gorkemarslan** [comment] 2021-10-02 17:49
@Vinit-Kumar-Shah, @rishabhjha708 has already created a new PR to solve this issue. Thus, I assigned @rishabhjha708 to this issue.
Could you introduce yourself in the discussion section? Then we can help you to find an appropriate issue.

**Comment by Vinit-Kumar-Shah** [comment] 2021-10-03 14:12
> @Vinit-Kumar-Shah, @rishabhjha708 has already created a new PR to solve this issue. Thus, I assigned @rishabhjha708 to this issue. Could you introduce yourself in the discussion section? Then we can help you to find an appropriate issue.

Sure, Thanks for your response

**Closed as completed** 2021-10-04 06:31 UTC
Labels: enhancement, help wanted, good first issue, code quality
